# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Jiawei Ge
title: Postdoctoral Researcher
email: jge9@jhu.edu & jg3642@columbia.edu
website: sonamyeshe.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: facespics
github_username:  sproogen
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: jameswgrant
linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: About Me
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  Hi, I'm Jiawei, a Ph.D. in Mechanical Engineering and a Medical Roboticist with over 8 years of experience advancing autonomy in robotic surgery. My work is dedicated to achieving higher levels of precision and efficiency, with a focus on autonomous robotic solutions for cancer surgery.
  
  I work with Professor Axel Krieger in the [IMERSE Lab](https://imerse.lcsr.jhu.edu), where we develop cutting-edge technologies to revolutionize robotic-assisted surgeries and improve patient outcomes.

content:
  - title: Research # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: >
          <div style="text-align: center;">
            <img src="https://raw.githubusercontent.com/SonamYeshe/sonamyeshe.github.io/master/images/glow_and_sew.JPG" alt="Glow and Sew" width="200" height="150" style="border-radius: 8px;">
          </div>
        # link: giving.jhu.edu/story/fluorescent-suture-could-help-surgeons
        # link_text: Project Website
        # additional_links:
        #  - title: Watch on YouTube
        #    icon: fab fa-youtube
        #    url: youtube.com/watch?v=fkAbShu2kCk
        # - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #   icon: fab fa-github
        #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        # quote: >
        #  A fluorescent suture could brighten up surgical outcomes.
        description: | # this will include new lines to allow paragraphs
          <b>A Fluorescent Suture and Surgical Planner for Image Guided Surgery</b>
          
          Justin D. Opfermann, <b>Jiawei Ge</b>, Yaning Wang, Minjae Do, Jin U. Kang, and Axel Krieger.

          <i>Student Design Showcase, Design of Medical Devices Conference, 2024.</i>
          
          Glow and Sew suture is coated in fluorescent powder that glows under near-infrared light, which is also able to penetrate through the blood and tissue, allowing surgeons to always see where their stitches are.

          Learn more about this initiative on <a href="https://giving.jhu.edu/story/fluorescent-suture-could-help-surgeons" style="color: #007BFF;" target="_blank">Johns Hopkins News</a> or <a href="https://youtube.com/watch?v=fkAbShu2kCk" style="color: #007BFF;" target="_blank">YouTube</a>.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: The Boring Company
        link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Senior Network System Administrator
        caption: November 2017 - Present
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Johns Hopkins University
        caption: 2017 - 2024
        sub_title: Ph.D. Mechanical Engineering
        quote: >
          Founded in 1876, Johns Hopkins University is widely recognized as America’s first research university, known for its rigorous scholarship, interdisciplinary collaboration, and leadership in science, engineering, and medicine.
        description: | # this will include new lines to allow paragraphs
          During my PhD at Johns Hopkins, I developed deep expertise in designing and executing independent research—from framing questions and building reproducible workflows to synthesizing results and communicating them clearly. The program strengthened my quantitative reasoning, scholarly writing, and collaboration skills, while teaching me to manage long-term projects against tight milestones.

          Beyond my dissertation, I engaged with the broader Hopkins community through seminars and cross-lab collaborations, and I adopted open, well-documented practices for code and data. The experience taught me to balance curiosity-driven exploration with practical impact and effective teamwork.
      - layout: left
        title: Columbia University
        caption: 2015 - 2017
        sub_title: M.S. Mechanical Engineering
        quote: >
          Founded in 1754, Columbia University is an Ivy League research university in New York City, renowned for rigorous scholarship, cross‑disciplinary innovation, and a global outlook—an ideal setting for advanced graduate study.
        description:
          TODO.
      - layout: left
        title: Huazhong University of Science and Technology (HUST)
        caption: 2011 - 2015
        sub_title: B.E. Mechanical Engineering
        quote: >
          Located in Wuhan, Huazhong University of Science and Technology (HUST) is one of China’s leading research universities, noted for its strength in engineering and applied sciences and a culture of rigorous, hands‑on innovation.
        description:
          TODO.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      <!-- Look at this cool image -->
      <!-- ![Trees](https://raw.githubusercontent.com/SonamYeshe/sonamyeshe.github.io/master/images/glow_and_sew.JPG) -->

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
