# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Jiawei Ge
title: Postdoctoral Researcher
email: jge9@jhu.edu & jg3642@columbia.edu
website: sonamyeshe.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
googlescholar_username: zMFXyfMAAAAJ
linkedin_username: jiawei-ge-phd-b29357114
orcid_username: 0000-0001-8336-1837
github_username: sonamyeshe
instagram_username: gejiawei88
# youtube_username: @sonamyeshe2492
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# xing_username: jekyll
# pinterest_username: jekyll
# googleplus_username: +jekyll

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: About Me
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  Hi, I'm Jiawei, a Ph.D. in Mechanical Engineering and a Medical Roboticist with over 8 years of experience advancing autonomy in robotic surgery. My work is dedicated to achieving higher levels of precision and efficiency, with a focus on autonomous robotic solutions for cancer surgery.
  
  I work with Professor Axel Krieger in the [IMERSE Lab](https://imerse.lcsr.jhu.edu), where we develop cutting-edge technologies to revolutionize robotic-assisted surgeries and improve patient outcomes.

content:
  - title: Research # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: >
          <div style="text-align: center;">
            <img src="https://raw.githubusercontent.com/SonamYeshe/sonamyeshe.github.io/master/images/2025_JMRR_Nephrectomy.JPG" alt="2025_JMRR_CAO_Resection" 
                 style="aspect-ratio: 4 / 3; width: 320px; border-radius: 8px;">
          </div>
        description: | # this will include new lines to allow paragraphs
          <a href="https://www.worldscientific.com/doi/abs/10.1142/S2424905X25500114" style="color: #007BFF;" target="_blank"><b>Towards Fluorescence-Guided Autonomous Robotic Partial Nephrectomy on Novel Tissue-Mimicking Hydrogel Phantoms</b></a>
          
          Ethan Kilmer<sup>†</sup>, Joseph Chen<sup>†</sup>, <b>Jiawei Ge</b>, Preksha Sarda, Richard Cha, Kevin Cleary, Lauren Shepard, Ahmed Ezzat Ghazi, Paul Maria Scheikl, and Axel Krieger.

          <i>Journal of Medical Robotics Research (JMRR), 2025.</i>
          
          We developed a fluorescence-guided autonomous robotic system, validated with novel hydrogel-based kidney phantoms, that enables precise resection of exophytic renal tumors with a clinically relevant margin accuracy of 1.44 mm in under 70 seconds.

          Learn more on <a href="https://youtu.be/4pGxCnDI8Hs" style="color: #007BFF;" target="_blank">Video Submission for JMRR/ISMR 2025</a>.
          
      - layout: left
        title: >
          <div style="text-align: center;">
            <img src="https://raw.githubusercontent.com/SonamYeshe/sonamyeshe.github.io/master/images/2025_JMRR_CAO_Resection.JPG" alt="2025_JMRR_CAO_Resection" 
                 style="aspect-ratio: 4 / 3; width: 320px; border-radius: 8px;">
          </div>
        description: | # this will include new lines to allow paragraphs
          <a href="https://www.worldscientific.com/doi/abs/10.1142/S2424905X25500084" style="color: #007BFF;" target="_blank"><b>Autonomous Vision-Guided Resection of Central Airway Obstruction</b></a>
          
          Mariana E. Smith<sup>†</sup>, Nural Yilmaz<sup>†</sup>, Tanner Watts, Paul Maria Scheikl, <b>Jiawei Ge</b>, Anton Deguet, Alan Kuntz, and Axel Krieger.

          <i>Journal of Medical Robotics Research (JMRR), 2025.</i>
          
          We propose a vision-guided, autonomous robotic system for precise palliative tracheal tumor resection, achieving over 90% volumetric tumor removal while maintaining a 1mm safety clearance from the tracheal surface in ex-vivo validation experiments.

          Learn more on <a href="https://youtu.be/Oh-Iq1PY3qY" style="color: #007BFF;" target="_blank">Video Submission for JMRR/ISMR 2025</a>.
          
      - layout: left
        title: >
          <div style="text-align: center;">
            <img src="https://raw.githubusercontent.com/SonamYeshe/sonamyeshe.github.io/master/images/2025_TMRB_Electrosurgery_MK.JPG" alt="2025_TMRB_Electrosurgery_MK" 
                 style="aspect-ratio: 4 / 3; width: 320px; border-radius: 8px;">
          </div>
        description: | # this will include new lines to allow paragraphs
          <a href="https://ieeexplore.ieee.org/abstract/document/11051047" style="color: #007BFF;" target="_blank"><b>Autonomous Closed-Loop Control for Robotic Soft Tissue Electrosurgery Using RGB-D Image Guidance</b></a>
          
          Michael Kam, <b>Jiawei Ge</b>, Naveed D Riaziat, Justin D Opfermann, Leila J Mady, Jeremy D Brown, Axel Krieger.

          <i>IEEE Transactions on Medical Robotics and Bionics (T-MRB), 2025.</i>
          
          We present an autonomous closed-loop robotic electrosurgery system that leverages 3D tissue tracking and image-based feedback control to enhance margin accuracy, achieving a 55% reduction in cutting error during tumor excision in ex vivo porcine tongue validation experiments.
          
      - layout: left
        title: >
          <div style="text-align: center;">
            <img src="https://raw.githubusercontent.com/SonamYeshe/sonamyeshe.github.io/master/images/2025_TMRB_Electrosurgery_HS.JPG" alt="2025_TMRB_Electrosurgery_HS" 
                 style="aspect-ratio: 4 / 3; width: 320px; border-radius: 8px;">
          </div>
        description: | # this will include new lines to allow paragraphs
          <a href="https://ieeexplore.ieee.org/abstract/document/10964360" style="color: #007BFF;" target="_blank"><b>A Confidence-Based Shared Control Strategy for Robotic Electrosurgery</b></a>
          
          Artmeio Meza-Pantoja, Andrew C. Lawson, Charlie C. Caputo, <b>Jiawei Ge</b>, Dale J. Cohen, Axel Krieger, Hamed Saeidi.

          <i>IEEE Transactions on Medical Robotics and Bionics (T-MRB), 2025.</i>
          
          We developed a shared control strategy for robotic electrosurgery, combining autonomous precision with human intervention to achieve more accurate soft tissue incisions and reduce human-in-the-loop time by 69.29% in validation experiments on porcine tongue samples.

          Learn more on <a href="https://youtu.be/mUrhwgW4a9Q" style="color: #007BFF;" target="_blank">Video Submission for TMRB 2025</a>.
          
      - layout: left
        title: >
          <div style="text-align: center;">
            <img src="https://raw.githubusercontent.com/SonamYeshe/sonamyeshe.github.io/master/images/2024_IROS_Nephrectomy.jpg" alt="2024_IROS_Nephrectomy" 
                 style="aspect-ratio: 4 / 3; width: 320px; border-radius: 8px;">
          </div>
        description: | # this will include new lines to allow paragraphs
          <a href="https://ieeexplore.ieee.org/abstract/document/10802114" style="color: #007BFF;" target="_blank"><b>Tracking Tumors under Deformation from Partial Point Clouds using Occupancy Networks</b></a>
          
          Pit Henrich<sup>†</sup>, Jiawei Liu<sup>†</sup>, <b>Jiawei Ge</b>, Samuel Schmidgall, Lauren Shepard, Ahmed Ezzat Ghazi, Franziska Mathis-Ullrich, Axel Krieger.

          <i>IEEE/RSJ International Conference on Intelligent Robots and Systems (IROS), 2024.</i>
          
          We developed an occupancy network-based approach for real-time tumor localization in deforming kidney phantoms during robot-assisted partial nephrectomy (RAPN), enabling accurate volumetric 3D tumor tracking at interactive speeds to enhance surgical precision.
          
      - layout: left
        title: >
          <div style="text-align: center;">
            <img src="https://raw.githubusercontent.com/SonamYeshe/sonamyeshe.github.io/master/images/2024_IROS_Glossectomy.PNG" alt="2024_IROS_Glossectomy" 
                 style="aspect-ratio: 4 / 3; width: 320px; border-radius: 8px;">
          </div>
        description: | # this will include new lines to allow paragraphs
          <a href="https://ieeexplore.ieee.org/abstract/document/10802347" style="color: #007BFF;" target="_blank"><b>Enhancing Surgical Precision in Autonomous Robotic Incisions via Physics-Based Tissue Cutting Simulation</b></a>
          
          <b>Jiawei Ge<sup>†</sup></b>, Ethan Kilmer<sup>†</sup>, Leila J Mady, Justin D Opfermann, Axel Krieger.

          <i>IEEE/RSJ International Conference on Intelligent Robots and Systems (IROS), 2024.</i>
          
          Integrated physics-based cutting simulations with the Autonomous System for Tumor Resection (ASTR) to enhance precision in soft tissue tumor surgeries by preoperatively predicting and compensating for tool-tissue interaction deformations.

          Learn more on <a href="https://youtu.be/QaNAIm-xUv0" style="color: #007BFF;" target="_blank">Oral Pitch Presentation video for IROS 2024</a>.
          
      - layout: left
        title: >
          <div style="text-align: center;">
            <img src="https://raw.githubusercontent.com/SonamYeshe/sonamyeshe.github.io/master/images/glow_and_sew.JPG" alt="Glow and Sew"
                  style="aspect-ratio: 4 / 3; width: 320px; border-radius: 8px;">
          </div>
        # link: giving.jhu.edu/story/fluorescent-suture-could-help-surgeons
        # link_text: Project Website
        # additional_links:
        #  - title: Watch on YouTube
        #    icon: fab fa-youtube
        #    url: youtube.com/watch?v=fkAbShu2kCk
        # - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #   icon: fab fa-github
        #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        # quote: >
        #  A fluorescent suture could brighten up surgical outcomes.
        description: | # this will include new lines to allow paragraphs
          <b>A Fluorescent Suture and Surgical Planner for Image Guided Surgery</b>
          
          Justin D. Opfermann, <b>Jiawei Ge</b>, Yaning Wang, Minjae Do, Jin U. Kang, and Axel Krieger.

          <i>Student Design Showcase, Design of Medical Devices Conference (DMD), 2024.</i>
          
          Glow and Sew suture is coated in fluorescent powder that glows under near-infrared light, which is also able to penetrate through the blood and tissue, allowing surgeons to always see where their stitches are.

          Learn more on <a href="https://giving.jhu.edu/story/fluorescent-suture-could-help-surgeons" style="color: #007BFF;" target="_blank">Johns Hopkins News</a>.
          
      - layout: left
        title: >
          <div style="text-align: center;">
            <img src="https://raw.githubusercontent.com/SonamYeshe/sonamyeshe.github.io/master/images/2024_ICRA_Glossectomy.png" alt="ASTR" 
                 style="aspect-ratio: 4 / 3; width: 320px; border-radius: 8px;">
          </div>
        description: | # this will include new lines to allow paragraphs
          <a href="https://ieeexplore.ieee.org/abstract/document/10354422" style="color: #007BFF;" target="_blank"><b>Autonomous System for Tumor Resection (ASTR) - Dual-Arm Robotic Midline Partial Glossectomy</b></a>
          
          <b>Jiawei Ge</b>, Michael Kam, Justin D. Opfermann, Hamed Saeidi, Simon Leonard, Leila J. Mady, Martin J. Schnermann, and Axel Krieger.

          <i>IEEE Robotics and Automation Letters (RA-L), 2024.</i>
          
          Introduced the development of the ASTR, a pioneering autonomous, dual-arm, vision-guided robotic system, specifically designed for the high-autonomy (level 4) surgical task of tumor resection.

          Learn more on <a href="https://engineering.jhu.edu/news/doctor-within-borders-robotic-surgeon-precisely-removes-cancerous-tumors" style="color: #007BFF;" target="_blank">Johns Hopkins News</a> or <a href="https://youtu.be/j16EoTRGxH8" style="color: #007BFF;" target="_blank">Oral Presentation video for ICRA 2024</a>.

      - layout: left
        title: >
          <div style="text-align: center;">
            <img src="https://raw.githubusercontent.com/SonamYeshe/sonamyeshe.github.io/master/images/2022_AIS_MPACT.JPG" alt="MPACT" 
                 style="aspect-ratio: 4 / 3; width: 320px; border-radius: 8px;">
          </div>
        description: | # this will include new lines to allow paragraphs
          <a href="https://advanced.onlinelibrary.wiley.com/doi/full/10.1002/aisy.202200072" style="color: #007BFF;" target="_blank"><b>Overcoming the Force Limitations of Magnetic Robotic Surgery: Magnetic Pulse Actuated Collisions for Tissue-Penetrating-Needle for Tetherless Interventions</b></a>
          
          Onder Erin, Xiaolong Liu, <b>Jiawei Ge</b>, Justin Opfermann, Yotam Barnoy, Lamar O. Mair, Jin U. Kang, William Gensheimer, Irving N. Weinberg, Yancy Diaz-Mercado, and Axel Krieger.

          <i>Advanced Intelligent Systems (AIS), 2022.</i>
          
          We propose the MPACT-Needle, a magnetically actuated impact force-based suture needle that achieves a 22.7-fold increase in penetration force with a 20x smaller volume, enabling precise tissue penetration for ultraminimally invasive surgical tasks such as suturing, corneal injections, and transscleral drug delivery.

          Learn more on <a href="https://youtu.be/y80xl7Zjnk0" style="color: #007BFF;" target="_blank">Video submission part 1</a> and <a href="https://youtu.be/HFYzS3b6fKw" style="color: #007BFF;" target="_blank">Video submission part 2</a> for AIS 2022.

      - layout: left
        title: >
          <div style="text-align: center;">
            <img src="https://raw.githubusercontent.com/SonamYeshe/sonamyeshe.github.io/master/images/2021_TMRB_Suture.JPG" alt="SUTURE" 
                 style="aspect-ratio: 4 / 3; width: 320px; border-radius: 8px;">
          </div>
        description: | # this will include new lines to allow paragraphs
          <a href="https://ieeexplore.ieee.org/abstract/document/9486920" style="color: #007BFF;" target="_blank"><b>Vaginal Cuff Closure With Dual-Arm Robot and Near-Infrared Fluorescent Sutures</b></a>
          
          Simon Leonard, Justin Opfermann, Nicholas Uebele, Lydia Carroll, Ryan Walter, Christopher Bayne, <b>Jiawei Ge</b>, Axel Krieger.

          <i>IEEE Transactions on Medical Robotics and Bionics (T-MRB), 2021.</i>
          
          We present a dual-arm suturing robotic system that integrates novel near-infrared fluorescent sutures and automates thread management, achieving superior performance and consistency compared to human surgeons in ex-vivo and in-vivo vaginal cuff closure experiments.

  - title: Ph.D. Thesis
    layout: list
    content:
      - layout: top-middle
        title: Advances in Medical Image Guided Autonomous Robotic Tumor Resection
        link: https://jscholarship.library.jhu.edu/items/be00cd4a-d801-41e9-83b1-b6a3e17bf0c8
      
#  - title: Experience # Title for the section
#    layout: list # Type of content section (list/text)
#    content:
#      - layout: left
#        title: The Boring Company
#        link: boringcompany.com
#        # link_text: boringcompany.com
#        sub_title: Senior Network System Administrator
#        caption: November 2017 - Present
#        quote: >
#          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
#        description: | # this will include new lines to allow paragraphs
#            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Johns Hopkins University
        caption: 2017 - 2024
        sub_title: Ph.D. Mechanical Engineering
        quote: >
          Founded in 1876, Johns Hopkins University is widely recognized as America’s first research university, known for its rigorous scholarship, interdisciplinary collaboration, and leadership in science, engineering, and medicine.
        description: | # this will include new lines to allow paragraphs
          During my PhD at Johns Hopkins, I developed deep expertise in designing and executing independent research—from framing questions and building reproducible workflows to synthesizing results and communicating them clearly. The program strengthened my quantitative reasoning, scholarly writing, and collaboration skills, while teaching me to manage long-term projects against tight milestones.

          Beyond my dissertation, I engaged with the broader Hopkins community through seminars and cross-lab collaborations, and I adopted open, well-documented practices for code and data. The experience taught me to balance curiosity-driven exploration with practical impact and effective teamwork.
      - layout: left
        title: Columbia University
        caption: 2015 - 2017
        sub_title: M.S. Mechanical Engineering
        quote: >
          Founded in 1754, Columbia University is an Ivy League research university in New York City, renowned for rigorous scholarship, cross‑disciplinary innovation, and a global outlook—an ideal setting for advanced graduate study.
        description: |
          It was great.
      - layout: left
        title: Huazhong University of Science and Technology (HUST)
        caption: 2011 - 2015
        sub_title: B.E. Mechanical Engineering
        quote: >
          Located in Wuhan, Huazhong University of Science and Technology (HUST) is one of China’s leading research universities, noted for its strength in engineering and applied sciences and a culture of rigorous, hands‑on innovation.
        description: |
          It was great.

#  - title: A Little More About Me
#    layout: text
#    content: | # this will include new lines to allow paragraphs
#      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
#      - Rock climbing
#      - Gaming
#      - Knitting
#      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

#      <!-- Look at this cool image -->
#      <!-- ![Trees](https://raw.githubusercontent.com/SonamYeshe/sonamyeshe.github.io/master/images/glow_and_sew.JPG) -->

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
